version: "3.7"
services:
  client:
    # where is the docker file
    build: client
    restart: always
    #command: python -m gunicorn --bind 0.0.0.0:5000 -w 3 project.app:app
    command: python -m flask run --host 0.0.0.0
    environment:
      - PYTHONBUFFERED=1
      - FLASK_APP=project.app

    ports:
      - 5000:5000
    networks:
      - DS_project
    depends_on:
      - user
  user:
    build: users
    #restart: always
    command: python -m flask run --host 0.0.0.0
    environment:
      - PYTHONBUFFERED=1
      - FLASK_APP=project.app
    ports:
      - 5001:5000
    networks:
          - DS_project
          - User_network
    depends_on:
          - user-db

  user-db: # production database
    image: postgres:13
    restart: always
    ports: # default postgres by default == 5432
      # map container port to local port of computer
      - 5432:5432
    networks:
      - User_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=usersDB # this matches with
    # to maintain info for a long time, now if you exit you will lose all info
    volumes:
      #- users_data:/var/lib/postgresql/data
      - ./users/project/db:/docker-entrypoint-initdb.d

  group:
    build: groups
    #restart: always
    command: python -m flask run --host 0.0.0.0
    environment:
      - PYTHONBUFFERED=1
      - FLASK_APP=project.app
    ports:
      - 5002:5000
    networks:
      - DS_project
      - Group_network
    depends_on:
      - group-db

  group-db: # production database
    image: postgres:13
    restart: always
    ports: # default postgres by default == 5432
      # map container port to local port of computer
      - 5433:5432
    networks:
      - Group_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=groupsDB # this matches with
    # to maintain info for a long time, now if you exit you will lose all info
    volumes:
      #- groups_data:/var/lib/postgresql/data
      - ./groups/project/db:/docker-entrypoint-initdb.d

  movie:
    build: movies
    #restart: always
    command: python -m flask run --host 0.0.0.0
    environment:
      - PYTHONBUFFERED=1
      - FLASK_APP=project.app
    ports:
      - 5003:5000
    networks:
      - DS_project
      - Movie_network
    depends_on:
      - movie-db

  movie-db: # production database
    image: postgres:13
    restart: always
    ports: # default postgres by default == 5432
      # map container port to local port of computer
      - 5434:5432
    networks:
      - Movie_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=moviesDB # this matches with
    # to maintain info for a long time, now if you exit you will lose all info
    volumes:
      #- movies_data:/var/lib/postgresql/data
      - ./movies/project/db:/docker-entrypoint-initdb.d
# specify network that this compose file should use
networks:
  DS_project:
  User_network:
  Group_network:
  Movie_network:
volumes:
  users_data:
  groups_data:
  movies_data:
