version: "3.7"
services:
  client:
    # where is the docker file
    build: client
    restart: always
    command: python -m gunicorn --bind 0.0.0.0:5000 -w 3 project.app:app
    ports:
      - 5000:5000
    environment:
      - DEBUG=0
    networks:
      - DS_project
    depends_on:
      - user
  user:
    build: users
    #restart: always
    command: python -m flask run --host 0.0.0.0
    environment:
      - PYTHONBUFFERED=1
      - FLASK_APP=project.app
    ports:
      - 5001:5000
    networks:
          - DS_project
          - User_network
    depends_on:
          - user-db

  user-db: # production database
    image: postgres:13
    restart: always
    ports: # default postgres by default == 5432
      # map container port to local port of computer
      - 5432:5432
    networks:
      - User_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=usersDB # this matches with
    # to maintain info for a long time, now if you exit you will lose all info
    volumes:
      #- users_data:/var/lib/postgresql/data
      - ./users/project/db:/docker-entrypoint-initdb.d
# specify network that this compose file should use
networks:
  DS_project:
  User_network:
volumes:
  users_data:
